In [3]:
import pandas as pd
pd=pd.read_csv("COVID19_line_list_data.csv")

In [4]:
pd.shape

(1085, 27)

In [5]:
pd.head()

,id,case_in_country,reporting date,Unnamed: 3,summary,location,country,gender,age,symptom_onset,...,recovered,symptom,source,link,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,1,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,"Shenzhen, Guangdong",China,male,66.0,01/03/20,...,0,NaN,Shenzhen Municipal Health Commission,http://wjw.sz.gov.cn/wzx/202001/t20200120_1898...,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,Shanghai,China,female,56.0,1/15/2020,...,0,NaN,Official Weibo of Shanghai Municipal Health Co...,https://www.weibo.com/2372649470/IqogQhgfa?fro...,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,1/21/2020,NaN,First confirmed imported cases in Zhejiang: pa...,Zhejiang,China,male,46.0,01/04/20,...,0,NaN,Health Commission of Zhejiang Province,http://www.zjwjw.gov.cn/art/2020/1/21/art_1202...,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,1/21/2020,NaN,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,female,60.0,NaN,...,0,NaN,人民日报官方微博,https://m.weibo.cn/status/4463235401268457?,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,1/21/2020,NaN,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,male,58.0,NaN,...,0,NaN,人民日报官方微博,https://m.weibo.cn/status/4463235401268457?,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
pd.columns

Index(['id', 'case_in_country', 'reporting date', 'Unnamed: 3', 'summary',
       'location', 'country', 'gender', 'age', 'symptom_onset',
       'If_onset_approximated', 'hosp_visit_date', 'exposure_start',
       'exposure_end', 'visiting Wuhan', 'from Wuhan', 'death', 'recovered',
       'symptom', 'source', 'link', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26'],
      dtype='object')

In [7]:
type(pd.sample(1))

pandas.core.frame.DataFrame

In [8]:
pd.dtypes

id                         int64
case_in_country          float64
reporting date            object
Unnamed: 3               float64
summary                   object
location                  object
country                   object
gender                    object
age                      float64
symptom_onset             object
If_onset_approximated    float64
hosp_visit_date           object
exposure_start            object
exposure_end              object
visiting Wuhan             int64
from Wuhan               float64
death                     object
recovered                 object
symptom                   object
source                    object
link                      object
Unnamed: 21              float64
Unnamed: 22              float64
Unnamed: 23              float64
Unnamed: 24              float64
Unnamed: 25              float64
Unnamed: 26              float64
dtype: object

In [9]:
pd.isnull().sum() #null values

id                          0
case_in_country           197
reporting date              1
Unnamed: 3               1085
summary                     5
location                    0
country                     0
gender                    183
age                       242
symptom_onset             522
If_onset_approximated     525
hosp_visit_date           578
exposure_start            957
exposure_end              744
visiting Wuhan              0
from Wuhan                  4
death                       0
recovered                   0
symptom                   815
source                      0
link                        0
Unnamed: 21              1085
Unnamed: 22              1085
Unnamed: 23              1085
Unnamed: 24              1085
Unnamed: 25              1085
Unnamed: 26              1085
dtype: int64

In [10]:
pd=pd.drop(['id','Unnamed: 21', 'Unnamed: 22','Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26'],axis=1)

In [11]:
pd.head()

,case_in_country,reporting date,Unnamed: 3,summary,location,country,gender,age,symptom_onset,If_onset_approximated,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,source,link
0,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,"Shenzhen, Guangdong",China,male,66.0,01/03/20,0.0,01/11/20,12/29/2019,01/04/20,1,0.0,0,0,NaN,Shenzhen Municipal Health Commission,http://wjw.sz.gov.cn/wzx/202001/t20200120_1898...
1,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,Shanghai,China,female,56.0,1/15/2020,0.0,1/15/2020,NaN,01/12/20,0,1.0,0,0,NaN,Official Weibo of Shanghai Municipal Health Co...,https://www.weibo.com/2372649470/IqogQhgfa?fro...
2,NaN,1/21/2020,NaN,First confirmed imported cases in Zhejiang: pa...,Zhejiang,China,male,46.0,01/04/20,0.0,1/17/2020,NaN,01/03/20,0,1.0,0,0,NaN,Health Commission of Zhejiang Province,http://www.zjwjw.gov.cn/art/2020/1/21/art_1202...
3,NaN,1/21/2020,NaN,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,female,60.0,NaN,NaN,1/19/2020,NaN,NaN,1,0.0,0,0,NaN,人民日报官方微博,https://m.weibo.cn/status/4463235401268457?
4,NaN,1/21/2020,NaN,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,male,58.0,NaN,NaN,1/14/2020,NaN,NaN,0,0.0,0,0,NaN,人民日报官方微博,https://m.weibo.cn/status/4463235401268457?

In [12]:
pd.values

array([[nan, '1/20/2020', nan, ..., nan,
        'Shenzhen Municipal Health Commission',
        'http://wjw.sz.gov.cn/wzx/202001/t20200120_18987787.htm'],
       [nan, '1/20/2020', nan, ..., nan,
        'Official Weibo of Shanghai Municipal Health Commission',
        'https://www.weibo.com/2372649470/IqogQhgfa?from=page_1001062372649470_profile&wvr=6&mod=weibotime&type=comment'],
       [nan, '1/21/2020', nan, ..., nan,
        'Health Commission of Zhejiang Province',
        'http://www.zjwjw.gov.cn/art/2020/1/21/art_1202101_41786033.html'],
       ...,
       [1.0, '2/26/2020', nan, ..., nan, 'South China Morning Post',
        'https://www.scmp.com/news/china/society/article/3052457/algeria-reports-first-coronavirus-case-italian-citizen'],
       [1.0, '2/25/2020', nan, ..., nan, 'Reuters',
        'https://www.reuters.com/article/us-croatia-coronavirus/croatia-confirms-its-first-case-of-coronavirus-infection-idUSKBN20J1OB'],
       [1.0, '2/25/2020', nan, ..., nan, 'Reuters',
        'https://www.reuters.com/article/uk-switzerland-coronavirus/swiss-authorities-confirm-first-case-of-coronavirus-idUSKBN20J1ZO']],
      dtype=object)

In [13]:
pd.select_dtypes("object")

,reporting date,summary,location,country,gender,symptom_onset,hosp_visit_date,exposure_start,exposure_end,death,recovered,symptom,source,link
0,1/20/2020,First confirmed imported COVID-19 pneumonia pa...,"Shenzhen, Guangdong",China,male,01/03/20,01/11/20,12/29/2019,01/04/20,0,0,NaN,Shenzhen Municipal Health Commission,http://wjw.sz.gov.cn/wzx/202001/t20200120_1898...
1,1/20/2020,First confirmed imported COVID-19 pneumonia pa...,Shanghai,China,female,1/15/2020,1/15/2020,NaN,01/12/20,0,0,NaN,Official Weibo of Shanghai Municipal Health Co...,https://www.weibo.com/2372649470/IqogQhgfa?fro...
2,1/21/2020,First confirmed imported cases in Zhejiang: pa...,Zhejiang,China,male,01/04/20,1/17/2020,NaN,01/03/20,0,0,NaN,Health Commission of Zhejiang Province,http://www.zjwjw.gov.cn/art/2020/1/21/art_1202...
3,1/21/2020,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,female,NaN,1/19/2020,NaN,NaN,0,0,NaN,人民日报官方微博,https://m.weibo.cn/status/4463235401268457?
4,1/21/2020,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,male,NaN,1/14/2020,NaN,NaN,0,0,NaN,人民日报官方微博,https://m.weibo.cn/status/4463235401268457?
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,2/25/2020,"new COVID-19 patient confirmed in Austria: 24,...",Innsbruck,Austria,NaN,NaN,NaN,NaN,NaN,0,0,NaN,Jakarta Post,https://www.thejakartapost.com/news/2020/02/25...
1081,2/24/2020,new COVID-19 patient confirmed in Afghanistan:...,Afghanistan,Afghanistan,NaN,NaN,NaN,NaN,NaN,0,0,NaN,Fox News,https://www.foxnews.com/health/afghanistan-fir...
1082,2/26/2020,new COVID-19 patient confirmed in Algeria: mal...,Algeria,Algeria,male,NaN,NaN,NaN,2/17/2020,0,0,NaN,South China Morning Post,https://www.scmp.com/news/china/society/articl...
1083,2/25/2020,new COVID-19 patient confirmed in Croatia: mal...,Croatia,Croatia,male,NaN,NaN,2/19/2020,2/21/2020,0,0,NaN,Reuters,https://www.reuters.com/article/us-croatia-cor...
1084,2/25/2020,new COVID-19 patient confirmed in Switzerland:...,Bern,Switzerland,male,2/17/2020,NaN,2/15/2020,2/15/2020,0,0,NaN,Reuters,https://www.reuters.com/article/uk-switzerland...

In [14]:
print(pd.shape[0])#To check the number of rows
print(pd.shape[1])# TO get the number of columns

1085
20

In [15]:
#To access the datatype of particular column
print(pd.dtypes[2])
print(pd.dtypes[-1])

float64
object

In [53]:
pd1=pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 20 columns):
case_in_country          888 non-null float64
reporting date           1084 non-null object
Unnamed: 3               0 non-null float64
summary                  1080 non-null object
location                 1085 non-null object
country                  1085 non-null object
gender                   902 non-null object
age                      843 non-null float64
symptom_onset            563 non-null object
If_onset_approximated    560 non-null float64
hosp_visit_date          507 non-null object
exposure_start           128 non-null object
exposure_end             341 non-null object
visiting Wuhan           1085 non-null int64
from Wuhan               1081 non-null float64
death                    1085 non-null object
recovered                1085 non-null object
symptom                  270 non-null object
source                   1085 non-null object
link                     1085 non-null object
dtypes: float64(5), int64(1), object(14)
memory usage: 169.7+ KB

# specific column DataType

- dataframe object does'nt have dtype
- series object have dtype and dtypes

In [17]:
# numericla columns

In [18]:
pd.age.mean() #mean

49.483689205219456

In [19]:
pd.age.mode()[0]

55.0

In [20]:
(pd.age.min(),pd.age.max()) #min,max functions

(0.25, 96.0)

In [21]:
#objec datatype
pd.country.dtype

dtype('O')

In [22]:
pd.country.count()

1085

In [23]:
pd.country.unique()

array(['China', 'France', 'Japan', 'Malaysia', 'Nepal', 'Singapore',
       'South Korea', 'Taiwan', 'Thailand', 'USA', 'Vietnam', 'Australia',
       'Canada', 'Cambodia', 'Sri Lanka', 'Germany', 'UAE', 'Hong Kong',
       'Italy', 'Russia', 'UK', 'India', 'Phillipines', 'Finland',
       'Spain', 'Sweden', 'Belgium', 'Egypt', 'Iran', 'Israel', 'Lebanon',
       'Kuwait', 'Bahrain', 'Austria', 'Afghanistan', 'Algeria',
       'Croatia', 'Switzerland'], dtype=object)

In [24]:
#how many unique country 
pd.country.nunique()

38

In [25]:
pd.country.value_counts()

China          197
Japan          190
South Korea    114
Hong Kong       94
Singapore       93
Germany         54
Thailand        41
France          39
Taiwan          34
Spain           34
Malaysia        23
UAE             21
UK              20
USA             18
Iran            18
Bahrain         17
Vietnam         16
Australia       15
Canada          12
Kuwait           9
Phillipines      3
India            3
Italy            3
Austria          2
Russia           2
Lebanon          1
Algeria          1
Switzerland      1
Belgium          1
Cambodia         1
Sweden           1
Israel           1
Egypt            1
Sri Lanka        1
Finland          1
Croatia          1
Afghanistan      1
Nepal            1
Name: country, dtype: int64

In [41]:
print(pd.country.unique()) # Unique countries
print(pd.index) # Indexes

['China' 'France' 'Japan' 'Malaysia' 'Nepal' 'Singapore' 'South Korea'
 'Taiwan' 'Thailand' 'USA' 'Vietnam' 'Australia' 'Canada' 'Cambodia'
 'Sri Lanka' 'Germany' 'UAE' 'Hong Kong' 'Italy' 'Russia' 'UK' 'India'
 'Phillipines' 'Finland' 'Spain' 'Sweden' 'Belgium' 'Egypt' 'Iran'
 'Israel' 'Lebanon' 'Kuwait' 'Bahrain' 'Austria' 'Afghanistan' 'Algeria'
 'Croatia' 'Switzerland']
RangeIndex(start=0, stop=1085, step=1)

In [27]:
pd.describe()

,case_in_country,Unnamed: 3,age,If_onset_approximated,visiting Wuhan,from Wuhan
count,888.000000,0.0,843.000000,560.000000,1085.000000,1081.000000
mean,48.841216,NaN,49.483689,0.042857,0.176959,0.144311
std,78.853528,NaN,18.255334,0.202716,0.381810,0.351567
min,1.000000,NaN,0.250000,0.000000,0.000000,0.000000
25%,11.000000,NaN,35.000000,0.000000,0.000000,0.000000
50%,28.000000,NaN,51.000000,0.000000,0.000000,0.000000
75%,67.250000,NaN,64.000000,0.000000,0.000000,0.000000
max,1443.000000,NaN,96.000000,1.000000,1.000000,1.000000

In [28]:
pd.describe(include=object) #to get the description for tthe categorical column

,reporting date,summary,location,country,gender,symptom_onset,hosp_visit_date,exposure_start,exposure_end,death,recovered,symptom,source,link
count,1084,1080,1085,1085,902,563,507,128,341,1085,1085,270,1085,1085
unique,43,967,156,38,2,70,60,39,52,14,32,108,85,490
top,2/27/2020,new confirmed COVID-19 patient in South Korea:,South Korea,China,male,1/23/2020,1/23/2020,1/26/2020,1/22/2020,0,0,fever,Ministry of Health,https://www.mhlw.go.jp/stf/houdou/houdou_list_...
freq,91,22,112,197,520,27,34,14,34,1022,926,73,179,88

In [29]:
import numpy as np
pd.describe(include=np.int64)

       visiting Wuhan
count     1085.000000
mean         0.176959
std          0.381810
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000

# slicing,subsettind,boolean Indexing
- position Based Index(iloc)
    - rows
    - columns
- Label Based Indexing(loc)

In [30]:
pd.iloc[1,:]

case_in_country                                                        NaN
reporting date                                                   1/20/2020
Unnamed: 3                                                             NaN
summary                  First confirmed imported COVID-19 pneumonia pa...
location                                                          Shanghai
country                                                              China
gender                                                              female
age                                                                     56
symptom_onset                                                    1/15/2020
If_onset_approximated                                                    0
hosp_visit_date                                                  1/15/2020
exposure_start                                                         NaN
exposure_end                                                      01/12/20
visiting Wuhan                                                           0
from Wuhan                                                               1
death                                                                    0
recovered                                                                0
symptom                                                                NaN
source                   Official Weibo of Shanghai Municipal Health Co...
link                     https://www.weibo.com/2372649470/IqogQhgfa?fro...
Name: 1, dtype: object

In [31]:
pd.iloc[1,5] #row with 1 and 5 column

'China'

In [33]:
pd.set_index("country").head(3) #To set particular column as index

,case_in_country,reporting date,Unnamed: 3,summary,location,gender,age,symptom_onset,If_onset_approximated,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,source,link
country,,,,,,,,,,,,,,,,,,,
China,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,"Shenzhen, Guangdong",male,66.0,01/03/20,0.0,01/11/20,12/29/2019,01/04/20,1,0.0,0,0,NaN,Shenzhen Municipal Health Commission,http://wjw.sz.gov.cn/wzx/202001/t20200120_1898...
China,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,Shanghai,female,56.0,1/15/2020,0.0,1/15/2020,NaN,01/12/20,0,1.0,0,0,NaN,Official Weibo of Shanghai Municipal Health Co...,https://www.weibo.com/2372649470/IqogQhgfa?fro...
China,NaN,1/21/2020,NaN,First confirmed imported cases in Zhejiang: pa...,Zhejiang,male,46.0,01/04/20,0.0,1/17/2020,NaN,01/03/20,0,1.0,0,0,NaN,Health Commission of Zhejiang Province,http://www.zjwjw.gov.cn/art/2020/1/21/art_1202...

In [49]:
#row wit index1 and all the columns
pd.iloc[1:2,:]

,case_in_country,reporting date,Unnamed: 3,summary,location,country,gender,age,symptom_onset,If_onset_approximated,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,source,link
1,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,Shanghai,China,female,56.0,1/15/2020,0.0,1/15/2020,NaN,01/12/20,0,1.0,0,0,NaN,Official Weibo of Shanghai Municipal Health Co...,https://www.weibo.com/2372649470/IqogQhgfa?fro...

In [50]:
# row with indices 1,2,3
pd.iloc[1:4,:]

,case_in_country,reporting date,Unnamed: 3,summary,location,country,gender,age,symptom_onset,If_onset_approximated,hosp_visit_date,exposure_start,exposure_end,visiting Wuhan,from Wuhan,death,recovered,symptom,source,link
1,NaN,1/20/2020,NaN,First confirmed imported COVID-19 pneumonia pa...,Shanghai,China,female,56.0,1/15/2020,0.0,1/15/2020,NaN,01/12/20,0,1.0,0,0,NaN,Official Weibo of Shanghai Municipal Health Co...,https://www.weibo.com/2372649470/IqogQhgfa?fro...
2,NaN,1/21/2020,NaN,First confirmed imported cases in Zhejiang: pa...,Zhejiang,China,male,46.0,01/04/20,0.0,1/17/2020,NaN,01/03/20,0,1.0,0,0,NaN,Health Commission of Zhejiang Province,http://www.zjwjw.gov.cn/art/2020/1/21/art_1202...
3,NaN,1/21/2020,NaN,new confirmed imported COVID-19 pneumonia in T...,Tianjin,China,female,60.0,NaN,NaN,1/19/2020,NaN,NaN,1,0.0,0,0,NaN,人民日报官方微博,https://m.weibo.cn/status/4463235401268457?

In [54]:
print(pd.isnull())

      case_in_country  reporting date  Unnamed: 3  summary  location  country  \
0                True           False        True    False     False    False
1                True           False        True    False     False    False
2                True           False        True    False     False    False
3                True           False        True    False     False    False
4                True           False        True    False     False    False
...               ...             ...         ...      ...       ...      ...
1080            False           False        True    False     False    False
1081            False           False        True    False     False    False
1082            False           False        True    False     False    False
1083            False           False        True    False     False    False
1084            False           False        True    False     False    False

      gender    age  symptom_onset  If_onset_approximated  hosp_visit_date  \
0      False  False          False                  False            False
1      False  False          False                  False            False
2      False  False          False                  False            False
3      False  False           True                   True            False
4      False  False           True                   True            False
...      ...    ...            ...                    ...              ...
1080    True  False           True                   True             True
1081    True  False           True                   True             True
1082   False   True           True                   True             True
1083   False   True           True                   True             True
1084   False  False          False                   True             True

      exposure_start  exposure_end  visiting Wuhan  from Wuhan  death  \
0              False         False           False       False  False
1               True         False           False       False  False
2               True         False           False       False  False
3               True          True           False       False  False
4               True          True           False       False  False
...              ...           ...             ...         ...    ...
1080            True          True           False       False  False
1081            True          True           False       False  False
1082            True         False           False       False  False
1083           False         False           False       False  False
1084           False         False           False       False  False

      recovered  symptom  source   link
0         False     True   False  False
1         False     True   False  False
2         False     True   False  False
3         False     True   False  False
4         False     True   False  False
...         ...      ...     ...    ...
1080      False     True   False  False
1081      False     True   False  False
1082      False     True   False  False
1083      False     True   False  False
1084      False     True   False  False

[1085 rows x 20 columns]

In [56]:
print(pd.isnull().sum()) #null values in each column

case_in_country           197
reporting date              1
Unnamed: 3               1085
summary                     5
location                    0
country                     0
gender                    183
age                       242
symptom_onset             522
If_onset_approximated     525
hosp_visit_date           578
exposure_start            957
exposure_end              744
visiting Wuhan              0
from Wuhan                  4
death                       0
recovered                   0
symptom                   815
source                      0
link                        0
dtype: int64